kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv01
  annotations:
        volume.beta.kubernetes.io/storage-class: "default"
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
