resources:
  - name: dev-client-repo
    type: git
    source:
      uri: git@example.com:example/MicroServiceClient.git
      branch: master
      repository: MicroServiceClient
      private_key: {{git-key}}

  - name: dev-server-repo
    type: git
    source:
      uri: git@example.com:example/MicroServiceServer.git
      branch: master
      repository: MicroServiceServer
      private_key: {{git-key}}
   
  - name: client-docker
    type: docker-image
    source:
      email: {{email}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_secret_access_key: {{aws-secret-access-key}}
      repository: example.docker-repo.com/teamy/client

  - name: server-docker
    type: docker-image
    source:
      email: {{email}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_secret_access_key: {{aws-secret-access-key}}
      repository: example.docker-repo.com/teamy/server

# Jobs start here

jobs:
  - name: client-tests
    plan:
    - get: dev-client-repo
      trigger: true
    - task: maven-tests
      file: dev-client-repo/ci/tasks/buildui.yml

  - name: server-tests
    plan:
      - get: dev-server-repo
        trigger: true
      - task: maven-tests
        file: dev-server-repo/ci/tasks/buildapi.yml 

  - name: client-build
    plan:
      - get: dev-client-repo
        passed: [client-tests]
        trigger: true
      - put: client-docker
        params:
          build: dev-client-repo
     
  - name: server-build
    plan:
      - get: dev-server-repo
        passed: [server-tests]
        trigger: true
      - put: server-docker
        params:
          build: dev-server-repo
