resources:
  - name: ops-repo
    type: git
    source:
      uri: git@github.com:Capgemini/portable-k8s-demo.git
      private_key: {{git-key}}
      paths: [ci/docker/*]

  - name: kops-docker
    type: docker-image
    source:
      email: {{email}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_secret_access_key: {{aws-secret-access-key}}
      repository: example.docker-repo.com/teamid/kube

# Jobs start here

jobs:
  - name: kops-image
    plan:
    - get: ops-repo
      trigger: true
    - put: kops-docker
      params:
        build: ops-repo/ci/docker
