apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-0
  namespace: kube-system
  labels:
    name: mongo-svc
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-port
  selector:
    name: mongo-svc-0

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-1
  namespace: kube-system
  labels:
    name: mongo-svc
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-port
  selector:
    name: mongo-svc-1

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-2
  namespace: kube-system
  labels:
    name: mongo-svc
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-port
  selector:
    name: mongo-svc-2

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-rc-0
  namespace: kube-system
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-svc-0
  template:
    metadata:
      labels:
        name: mongo-svc-0
    spec:
      containers:
      - name: mongo-svc-0
        image: example.docker-repo.com/kube-mongo:beta
        env:
          - name: mongo_node_name
            value: mongo-svc-0
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage-0
          mountPath: /data/db
      volumes:
      - name: mongo-storage-0
        emptyDir: {}
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-rc-1
  namespace: kube-system
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-svc-1
  template:
    metadata:
      labels:
        name: mongo-svc-1
    spec:
      containers:
      - name: mongo-svc-1
        image: example.docker-repo.com/kube-mongo:beta
        env:
          - name: mongo_node_name
            value: mongo-svc-1
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage-1
          mountPath: /data/db
      volumes:
      - name: mongo-storage-1
        emptyDir: {}

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-rc-2
  namespace: kube-system
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-svc-2
  template:
    metadata:
      labels:
        name: mongo-svc-2
    spec:
      containers:
      - name: mongo-svc-2
        image: example.docker-repo.com/kube-mongo:beta
        env:
          - name: mongo_node_name
            value: mongo-svc-2
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage-2
          mountPath: /data/db
      volumes:
      - name: mongo-storage-2
        emptyDir: {}
